apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #schedulerName: default-scheduler
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.1"
              memory: 2Gi
            requests:
              cpu: "0.1"
              memory: 2Gi
