apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
profiles:
  - schedulerName: default-scheduler
    plugins:
      filter:
        enabled:
          - name: dynamic
    pluginConfig:
      - name: dynamic
        args:
          toleranceCPURate: 80
          toleranceMemoryRate: 80